[gcloud]
format = 'on [$symbol$active]($style) '
style = 'bold yellow'
detect_env_vars = ["CLOUDSDK_ACTIVE_CONFIG_NAME"]

[kubernetes]
# disabled by default
disabled = false

[kubernetes.context_aliases]
# OpenShift contexts carry the namespace and user in the kube context: `namespace/name/user`:
'.*/openshift-cluster/.*' = 'openshift'
# Or better, to rename every OpenShift cluster at once:
'.*/(?P<var_cluster>[\w-]+)/.*' = '$var_cluster'

# Contexts from GKE, AWS and other cloud providers usually carry additional information, like the region/zone.
# The following entry matches on the GKE format (`gke_projectname_zone_cluster-name`)
# and renames every matching kube context into a more readable format (`gke-cluster-name`):
'gke_.*_(?P<var_cluster>[\w-]+)' = 'gke-$var_cluster'

[custom.task-ps1]
command = "echo $TASK_CONTEXT"
when = ''' test $TASK_CONTEXT != "" '''
format = 'updating [$output]($style) '

[custom.savvy]
when = ''' test $SAVVY_CONTEXT != "" ''' 
symbol = '😎'
format = 'savvy [$symbol$active]($style) '



